// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
import { Fountain } from './tokenizer.js';
export const parser = LRParser.deserialize({
  version: 14,
  states:
    ".WO!_OROOO!fOPO'#DfO!kOPO'#ClO!sORO'#CtO!sORO'#CvO!sORO'#CxO!sORO'#CzO!sORO'#C}O#_ORO'#CsOOOP'#Cs'#CsO!sORO'#CqOOOP'#Di'#DiO$rORO'#CpO$uORO'#DSO$uORO'#DUO$|ORO'#D]O%UOQO'#DWO%aOQO'#DVO%fOQO'#D[O%qOQO'#DZO%vORO'#D^OOOP'#Do'#DoO&TORO'#DbO$uORO'#DcO&bOQO'#DdO&gOQO'#DeOOOP'#Co'#CoO&lORO'#CnOOOP'#Dg'#DgQQOROOOQOROOO&sOQO,5:QOOOP-E7d-E7dO&xOPO,59WO'fORO,59`OOOP'#Dj'#DjO(UORO,59bO(tORO,59dO)dORO,59fO)kORO,59iO)rORO,59]OOOP-E7g-E7gOOOP,59[,59[O)yORO,59nO*TORO,59pO*bOQO,59oOOOP,59w,59wOOOO'#Dk'#DkO*gOQO,59rO*rORO,59qO*yOQO,59vO*rORO,59uOOOP'#Dm'#DmO+UORO,59xO+cOSO'#D_OOOP,59x,59xO+kOQO,59xO+pORO,59|OOOP-E7m-E7mOOOP,59|,59|O+zORO,59}OOOP,5:O,5:OOOOP,5:P,5:POOOP'#Dh'#DhO,UORO,59YOOOP,59Y,59YOOOP-E7e-E7eOOOP1G/l1G/lOOOP1G.r1G.rO,]ORO1G.zOOOP-E7h-E7hO-ZORO1G.|O.XORO1G/OO/VORO1G/QOOOP1G/T1G/TOOOP1G.w1G.wOOOP1G/Y1G/YOOOP1G/Z1G/ZOOOO-E7i-E7iO0TORO'#DXO!sORO'#DYO0[OQO'#DlO0aORO1G/]O1^ORO1G/aOOOP-E7k-E7kOOOP1G/d1G/dO2ZOQO1G/dOOOO'#Dn'#DnO2`OSO,59yOOOO,59y,59yOOOP1G/h1G/hOOOP1G/i1G/iOOOP-E7f-E7fOOOP1G.t1G.tO2hORO,59tOOOP,5:W,5:WOOOP-E7j-E7jOOOP7+%O7+%OOOOO-E7l-E7lOOOO1G/e1G/eOOOO1G/`1G/`",
  stateData:
    "2|~OP]OQiORbOU`OVhOWgOXdOY^O[kO^jOfYOiROkSOmTOoUOpXOrVOtXO!SeO~OSPO~PQOToO~OSPO^qO~O[kOiROkSOmTOoUOpXOrVOtXO~OP!ZXQ!ZXR!ZXU!ZXV!ZXW!ZXX!ZXY!ZX[gX^!ZXagXfgXigXkgXmgXogXpgXrgXtgX!S!ZX!d!ZX~OazOfYO~P!sOZ}Oa!OO~OfYOt!POazX~Oa!RO~OfYOt!POa!OX~Oa!TO~Oa!XOfYO!S!WO~P!sOa!]OfYO!SeO~P!sOa!_O~Oa!`O~O]!cO~PQOa!eO~O^!fO~O[kOkSOmTOoUOpXOrVOtXO~Oi!gO~P&}O[kOiROmTOoUOpXOrVOtXO~Ok!iO~P'mO[kOiROkSOoUOpXOrVOtXO~Om!jO~P(]O[kOiROkSOmTOpXOrVOtXO~Oo!kO~P({Os!lO~P!sOu!mO~P!sOa!nOfYO~P!sOfYOZxaaxa~P!sOa!oO~OfYOt!POaza~Of!rO~P!sOfYOt!POa!Oa~Oa!wOfYO!S!WO~P!sO!S!{O!T!yO~Oa!wO~Oa!|OfYO~P!sOa!}OfYO~P!sO]#PO~PQO[kOahifhiihikhimhiohiphirhithishiuhiZhi!Shi~O[kOajifjiijikjimjiojipjirjitjisjiujiZji!Sji~O[kOalifliiliklimlioliplirlitlisliuliZli!Sli~O[kOanifniiniknimnionipnirnitnisniuniZni!Sni~Oa{X~P!sOa#RO~Of!rOPyiQyiRyiUyiVyiWyiXyiYyi^yi!Syi!dyi]yi~P!sOf!rOP}iQ}iR}iU}iV}iW}iX}iY}i^}i!S}i!d}i]}i~P!sOa#TO~O!S#VO!T!yO~Ou#WO~P!sOrs!Sfukmoitpk~",
  goto: ")n!dPPPPPPPPPPPPPPPP!eP!h#e#n#uP$a%`P%`P%`P%`PP%`PPPP#n#n&V#n&^&e&e#n&k#n#n&rPP#n#n#n#n&x'O'V']'w(r(|)W)^)dRnOUWOmn!kXRSTUVY[]^dfgkrtuvwx{|!R!T!V!Z!^!b!g!i!j!k!q!r!t!u#QUlOmnT!ak!bZjOkmn!blZO[]^fgkmn{|!Z!^!bW!P`b!Q!ST!Ud!VlZO[]^fgkmn{|!Z!^!b!OsRSTUVYrtuvwx!R!T!g!i!j!k!q!r!t!u#QT!Ud!V!iXORSTUVY[]^dfgkmnrtuvwx{|!R!T!V!Z!^!b!q!r!t!u#QZ_Okmn!bZaOkmn!bX!s!R!T!t!uZcOkmn!bQ!YdR!x!VQQORpQSmOnR!dmQ!bkR#O!bY[Okmn!bYy[{|!Z!^Q{]Q|^Q!ZfR!^gSrR!gStS!iSuT!jSvU!kQwVQxY`!hrtuvwx!q#QW!q!R!T!t!uR#Q!rQ!Q`Q!SbT!p!Q!SQ!t!RQ!u!TT#S!t!uQ!VdR!v!VQ!z!WR#U!zYfOkmn!bR![f",
  nodeNames:
    '⚠ ForceActionMark PageBreak DualCharacter TitleKey TitleValue Character Transition SynopsisMark SceneHeading GreaterThan LessThan BoneStart BoneEnd EmptyLine Screenplay TitlePage Newline Boneyard Element ActionLine LineParenthetical LParen Inline Underline Underscore ItalicBold TripleAsterisks Bold DoubleAsterisks Italic SingleAsterisk PlainText Note NoteStart NoteEnd WhiteSpace RParen ForcedActionLine CenterLine ForceRight CharacterBlock CharacterCue DialogueLine Parenthetical DualCharacterBlock DualCharacterCue ForceTransition SceneHeadingLine SceneNumber SectionMark Numbers SectionLine SynopsisLine TransitionLine PageBreakLine',
  maxTerm: 66,
  skippedNodes: [0],
  repeatNodeCount: 10,
  tokenData:
    "&V~RdOY!aYZ#XZp!apq#^qs!ast$Qtx!axy$Vyz$[z{$a{!P!a!Q![$v![!^!a!_!}!a!}#O%j#P#Q%u#R#S&Q#S;'S!a;'S;=`#R<%lO!aP!fXpPOY!aZs!atx!a{!P!a!Q!^!a!_!}!a#S;'S!a;'S;=`#R<%lO!aP#UP;=`<%l!a~#^Oa~~#eXt~pPOY!aZs!atx!a{!P!a!Q!^!a!_!}!a#S;'S!a;'S;=`#R<%lO!a~$VO!S~~$[Of~~$aOu~~$fPo~z{$i~$nPm~z{$q~$vOk~R$}X!TQpPOY!aZs!atx!a{!P!a!Q!^!a!_!}!a#S;'S!a;'S;=`#R<%lO!a~%mP!}#O%p~%uOr~~%xP#P#Q%{~&QOs~~&VOi~",
  tokenizers: [Fountain, 0, 1],
  topRules: { Screenplay: [0, 15] },
  tokenPrec: 813,
});
